general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    color = rgba(1f2430ff)

    blur_passes = 2
    blur_size = 5
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(cbccc6ff)
    font_size = 72
    font_family = JetBrainsMono Nerd Font

    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgba(707a8cff)
    font_size = 14
    font_family = JetBrainsMono Nerd Font

    position = 0, 35
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 42

    outline_thickness = 1

    dots_size = 0.20
    dots_spacing = 0.30
    dots_center = true

    outer_color = rgba(3e4a5cff)
    inner_color = rgba(242936ff)
    font_color = rgba(cbccc6ff)

    check_color = rgba(73d0ffff)
    fail_color = rgba(f28779ff)

    fade_on_empty = false

    placeholder_text = <span foreground="##707a8c">Password</span>

    position = 0, -70
    halign = center
    valign = center
}
